#pragma once

/// @file automation_helpers.h
/// @brief Inline helper functions called from ESPHome YAML lambdas.
/// Bridges the gap between YAML automations and the C++ VentilationController /
/// VentilationLogic classes.  Also declares all `extern` pointers that ESPHome
/// code-gen provides for globals, scripts, lights, outputs, fan, etc.

#include "esphome.h"
#include <string>
#include <vector>

// Core and Component Headers
#include "esphome/components/globals/globals_component.h"
#include "esphome/components/script/script.h"
#include "esphome/components/template/select/template_select.h"
#include "esphome/components/template/number/template_number.h"
#include "esphome/components/template/switch/template_switch.h"
#include "esphome/components/fan/fan.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/output/float_output.h"
#include "esphome/components/light/light_state.h"
// Custom Component Header
#include "esphome/components/ventilation_group/ventilation_group.h"
#include "esphome/components/ventilation_logic/ventilation_logic.h"

// --- Extern declarations -----------------------------------------------
// Generated by ESPHome code-gen; IDs must match YAML component `id:` values.

/// @name Global variables
/// @{
extern esphome::globals::GlobalsComponent<bool> *system_on;            ///< Master power state.
extern esphome::globals::GlobalsComponent<bool> *ventilation_enabled;   ///< Ventilation enabled flag.
extern esphome::globals::GlobalsComponent<int> *current_mode_index;     ///< Active mode index (0–3).
extern esphome::globals::GlobalsComponent<int> *fan_intensity_level;    ///< Fan intensity (1–10).
extern esphome::globals::RestoringGlobalsComponent<bool> *co2_auto_enabled;      ///< CO2 auto-control enabled flag.
extern esphome::globals::RestoringGlobalsComponent<int> *co2_min_fan_level;      ///< Min fan level for CO2 control (moisture protection).
extern esphome::globals::RestoringGlobalsComponent<int> *co2_max_fan_level;      ///< Max fan level for CO2 control (noise limit).
/// @}

/// @name Template UI components
/// @{
extern esphome::template_::TemplateSelect *selected_mode;       ///< Mode selector (WRG/Stoß/Durchlüften/Aus).
extern esphome::template_::TemplateSelect *fan_mode_select;     ///< Fan hardware mode (4-Pin / 3-Pin).
extern esphome::template_::TemplateNumber *vent_timer;          ///< Ventilation timer (minutes).
extern esphome::template_::TemplateNumber *fan_intensity_display; ///< Fan intensity display number.
extern esphome::template_::TemplateSwitch *fan_direction;       ///< Manual direction override switch.
extern esphome::template_::TemplateSwitch *co2_auto_switch;     ///< CO2 auto-control on/off switch.
/// @}

/// @name Scripts
/// @{
extern esphome::script::RestartScript<> *update_leds;         ///< Refreshes all status LEDs.
extern esphome::script::RestartScript<> *fan_speed_update;    ///< Re-applies fan speed.
extern esphome::script::SingleScript<float, int> *set_fan_speed_and_direction; ///< Sets PWM + direction.
/// @}

/// @name Fan hardware
/// @{
extern esphome::speed::SpeedFan *lueftung_fan;       ///< Main fan (speed platform).
extern esphome::ledc::LEDCOutput *fan_pwm_primary;   ///< Primary PWM output (GPIO19).
extern esphome::ledc::LEDCOutput *fan_pwm_secondary;  ///< Secondary PWM output (GPIO18).
/// @}

/// @name Sensors
/// @{
extern esphome::sensor::Sensor *co2_sensor;          ///< SCD41 CO2 sensor.
/// @}

/// @name Status LEDs (monochromatic light components)
/// @{
extern esphome::light::LightState *status_led_l1;        ///< Level indicator LED 1.
extern esphome::light::LightState *status_led_l2;        ///< Level indicator LED 2.
extern esphome::light::LightState *status_led_l3;        ///< Level indicator LED 3.
extern esphome::light::LightState *status_led_l4;        ///< Level indicator LED 4.
extern esphome::light::LightState *status_led_l5;        ///< Level indicator LED 5.
extern esphome::light::LightState *status_led_power;     ///< Power status LED.
extern esphome::light::LightState *status_led_master;    ///< Master status LED (reserved).
extern esphome::light::LightState *status_led_mode_wrg;  ///< Mode LED: Wärmerückgewinnung.
extern esphome::light::LightState *status_led_mode_vent; ///< Mode LED: Ventilation.
/// @}

/// Ventilation controller component instance.
extern esphome::VentilationController *ventilation_ctrl;

// --- Inline wrappers (called from YAML lambdas) -----------------------

/// @brief Delegates IAQ classification to VentilationLogic.
inline std::string get_iaq_classification(float iaq_val) {
  return VentilationLogic::get_iaq_classification(iaq_val);
}

/// @brief Returns a human-readable German CO2 classification.
inline std::string get_co2_classification(float co2_ppm) {
  return VentilationLogic::get_co2_classification(co2_ppm);
}

/// @brief Calculates CO2-based fan level with hysteresis.
inline int get_co2_fan_level(float co2_ppm, int current_level, int min_level, int max_level) {
  return VentilationLogic::get_co2_fan_level(co2_ppm, current_level, min_level, max_level);
}

/// @brief Applies CO2-based auto-control if enabled and SCD41 is connected.
/// Checks sensor availability (NaN = not connected), calculates target level,
/// and applies it only if it differs from the current level (gradual change).
inline void apply_co2_auto_control() {
    // Guard: CO2 auto-control must be enabled
    if (!co2_auto_enabled->value()) return;

    // Guard: System must be on
    if (!ventilation_enabled->value()) return;

    // Guard: SCD41 sensor must be connected (state is NaN when absent)
    if (co2_sensor == nullptr) return;
    float co2_ppm = co2_sensor->state;
    if (std::isnan(co2_ppm)) {
        ESP_LOGD("co2_auto", "SCD41 not connected — CO2 auto-control inactive");
        return;
    }

    int current_level = fan_intensity_level->value();
    int min_level = co2_min_fan_level->value();
    int max_level = co2_max_fan_level->value();

    int target_level = VentilationLogic::get_co2_fan_level(co2_ppm, current_level, min_level, max_level);

    if (target_level != current_level) {
        ESP_LOGI("co2_auto", "CO2=%.0f ppm → Fan %d→%d (min=%d, max=%d)",
                 co2_ppm, current_level, target_level, min_level, max_level);
        fan_intensity_level->value() = target_level;
        fan_intensity_display->publish_state(target_level);
        ventilation_ctrl->set_fan_intensity(target_level);
        fan_speed_update->execute();
        update_leds->execute();
    }
}


/// @brief Returns an IAQ traffic-light RGB vector for ESP-NOW visualization.
inline std::vector<uint8_t> get_iaq_traffic_light_data(float iaq_val) {
  return VentilationLogic::get_iaq_traffic_light_data(iaq_val);
}

/// @brief Sets fan PWM based on mode (4-pin/3-pin), speed, and direction.
/// Handles specific logic for AxiRev (PWM direction) vs VarioPro (Dual-GND switching).
/// @param speed      Target speed duty cycle (0.0 to 1.0).
/// @param direction  Target direction (0 = Direction A/In, 1 = Direction B/Out).
inline void set_fan_logic(float speed, int direction) {
    if (fan_mode_select == nullptr || fan_pwm_primary == nullptr || fan_pwm_secondary == nullptr) {
        return; // Safety guard
    }

    std::string mode = fan_mode_select->state;

    if (mode == "4-Pin PWM") {
        // 4-Pin Mode (AxiRev): Use PWM duty cycle for speed AND direction
        // AxiRev Specification:
        // - 0-49% Duty: Direction A (intake), speed increases with PWM
        // - 50% Duty: Neutral (stopped)
        // - 51-100% Duty: Direction B (exhaust), speed increases with PWM
        
        float axirev_duty;
        
        if (direction == 0) {
            // Direction A: Map speed to 0-49% range
            // speed 0.0 -> 0%, speed 1.0 -> 49%
            axirev_duty = speed * 0.49f;
        } else {
            // Direction B: Map speed to 51-100% range
            // speed 0.0 -> 51%, speed 1.0 -> 100%
            axirev_duty = 0.51f + (speed * 0.49f);
        }
        
        fan_pwm_primary->set_level(axirev_duty);
        fan_pwm_secondary->set_level(0.0);  // Ensure GND2 is OFF
        
    } else if (mode == "3-Pin Dual-GND") {
        // 3-Pin Dual-GND Mode: Switch between GND1 and GND2
        
        // Map speed to VarioPro voltage range (7V-12V = 58%-100%)
        float variopro_duty = 0.58f + speed * 0.42f;
        
        if (direction == 0) {
            // Direction A: Activate GND1, deactivate GND2
            fan_pwm_secondary->set_level(0.0);
            delayMicroseconds(100);  // 100µs safety delay for MOSFET switching
            fan_pwm_primary->set_level(variopro_duty);
        } else {
            // Direction B: Activate GND2, deactivate GND1
            fan_pwm_primary->set_level(0.0);
            delayMicroseconds(100);  // 100µs safety delay for MOSFET switching
            fan_pwm_secondary->set_level(variopro_duty);
        }
    }
}

/// @brief Updates fan speed and direction based on intensity and mode.
/// Calculates PWM using fan_intensity_level and fan_direction.
inline void update_fan_logic() {
    if (fan_intensity_level == nullptr || fan_direction == nullptr) return;

    int intensity = fan_intensity_level->value();
    
    // Convert intensity (1-10) to speed (0.0-1.0)
    float speed = (intensity - 1.0f) / 9.0f;
    if (speed < 0.0f) speed = 0.0f;
    if (speed > 1.0f) speed = 1.0f;

    // Get direction from fan_direction switch
    int direction = fan_direction->state ? 1 : 0;

    set_fan_logic(speed, direction);
}

/// @brief Calculates heat-recovery efficiency as a percentage.
inline float calculate_heat_recovery_efficiency(float t_raum, float t_zuluft, float t_aussen) {
  return VentilationLogic::calculate_heat_recovery_efficiency(t_raum, t_zuluft, t_aussen);
}


/// @brief Returns true if the manual speed slider is below the off threshold.
inline bool is_fan_slider_off(float value) {
    return VentilationLogic::is_fan_slider_off(value);
}


/// @brief Linear ramp-up for soft fan start (0.0…1.0 over 100 iterations).
inline float calculate_ramp_up(int iteration) {
    return VentilationLogic::calculate_ramp_up(iteration);
}

/// @brief Linear ramp-down for soft fan stop (1.0…0.0 over 100 iterations).
inline float calculate_ramp_down(int iteration) {
    return VentilationLogic::calculate_ramp_down(iteration);
}


/// @brief Applies the operating mode corresponding to the given index.
/// Index mapping: 0 = Wärmerückgewinnung, 1 = Stoßlüftung,
/// 2 = Durchlüften (uses vent_timer), 3 = Aus.
inline void cycle_operating_mode(int mode_index) {
  auto *v = ventilation_ctrl;
  
  switch(mode_index) {
    case 0:  // Wärmerückgewinnung
      v->set_mode(esphome::MODE_ECO_RECOVERY);
      break;
    case 1:  // Stoßlüftung
      v->set_mode(esphome::MODE_STOSSLUEFTUNG);
      break;
    case 2:  // Durchlüften — timer from vent_timer number component
      v->set_mode(esphome::MODE_VENTILATION, (uint32_t)(vent_timer->state * 60 * 1000));
      break;
    case 3:  // Aus
      v->set_mode(esphome::MODE_OFF);
      break;
  }
}


/// @brief Refreshes all status LEDs based on system_on, current mode, and fan level.
/// Maps fan intensity 1–10 onto the 5 level LEDs and toggles the two mode LEDs.
inline void update_leds_logic() {
  auto *v = ventilation_ctrl;
  int current_mode = v->state_machine.current_mode;

  // 1. Power LED (Always ON if system is ON)
  if (system_on->value()) {
    status_led_power->turn_on();
  } else {
     // Optional: Blink or Off? Let's keep it OFF for now
    status_led_power->turn_off();
  }

  // 2. Mode LEDs
  status_led_mode_wrg->turn_off();
  status_led_mode_vent->turn_off();
  
  if (system_on->value()) {
    if (current_mode == esphome::MODE_ECO_RECOVERY) {
      // WRG: Left LED on
      status_led_mode_wrg->turn_on();
    } else if (current_mode == esphome::MODE_STOSSLUEFTUNG) {
      // Stoßlüftung: Right LED on
      status_led_mode_vent->turn_on();
    } else if (current_mode == esphome::MODE_VENTILATION) {
      // Durchlüften: Both LEDs on
      status_led_mode_wrg->turn_on();
      status_led_mode_vent->turn_on();
    }
    // MODE_OFF: Both LEDs off (already reset above)
  }

  // 3. Level LEDs (1-10 mapped to 5 LEDs)
  // Reset all first
  status_led_l1->turn_off();
  status_led_l2->turn_off();
  status_led_l3->turn_off();
  status_led_l4->turn_off();
  status_led_l5->turn_off();

  if (!system_on->value() || current_mode == esphome::MODE_OFF) return;

  int level = fan_intensity_level->value();
  
  // Mapping Logic (1-10 -> 5 LEDs)
  if (level >= 10) {
    status_led_l1->turn_on(); status_led_l2->turn_on();
    status_led_l3->turn_on(); status_led_l4->turn_on();
    status_led_l5->turn_on();
  } else {
     switch(level) {
       case 1: status_led_l1->turn_on(); break;
       case 2: status_led_l1->turn_on(); status_led_l2->turn_on(); break;
       case 3: status_led_l2->turn_on(); break;
       case 4: status_led_l2->turn_on(); status_led_l3->turn_on(); break;
       case 5: status_led_l3->turn_on(); break;
       case 6: status_led_l3->turn_on(); status_led_l4->turn_on(); break;
       case 7: status_led_l4->turn_on(); break;
       case 8: status_led_l4->turn_on(); status_led_l5->turn_on(); break;
       case 9: status_led_l5->turn_on(); break;
     }
  }
}

/// @brief Handles an incoming ESP-NOW packet.
/// Delegates parsing to VentilationController, then updates UI globals,
/// select component, LEDs, and fan speed if state changed.
inline void handle_espnow_receive(std::vector<uint8_t> data) {
    auto *v = ventilation_ctrl;
    bool changed = v->on_packet_received(data);

    if (changed) {
        // 1. Sync Fan Intensity
        if (v->current_fan_intensity != fan_intensity_level->value()) {
            fan_intensity_level->value() = v->current_fan_intensity;
            fan_intensity_display->publish_state(v->current_fan_intensity);
        }

        // 2. Sync Mode & Globals
        int new_mode_idx = 0;
        std::string mode_str = "Wärmerückgewinnung";

        if (v->state_machine.current_mode == esphome::MODE_OFF) {
            new_mode_idx = 3; mode_str = "Aus";
            ventilation_enabled->value() = false;
            system_on->value() = false;
        } else {
            ventilation_enabled->value() = true;
            system_on->value() = true;
            if (v->state_machine.current_mode == esphome::MODE_ECO_RECOVERY) { new_mode_idx = 0; mode_str = "Wärmerückgewinnung"; }
            else if (v->state_machine.current_mode == esphome::MODE_STOSSLUEFTUNG) { new_mode_idx = 1; mode_str = "Stoßlüftung"; }
            else if (v->state_machine.current_mode == esphome::MODE_VENTILATION) { new_mode_idx = 2; mode_str = "Durchlüften"; }
        }

        current_mode_index->value() = new_mode_idx;

        // Update Select Component if different
        if (selected_mode->current_option() != mode_str) {
            selected_mode->publish_state(mode_str);
        }

        // Update Visuals
        update_leds->execute();
        fan_speed_update->execute();
    }
}

/// @brief Updates the ventilation duration on-the-fly without switching mode.
/// Called when the user adjusts the vent_timer number component.
inline void set_ventilation_timer(float value) {
    auto *v = ventilation_ctrl;
    uint32_t ms = (uint32_t)value * 60 * 1000;
    // Update the duration but keep current mode
    v->state_machine.ventilation_duration_ms = ms;
}

/// @brief Converts a seconds value from the UI slider to ms and updates cycle duration.
inline void set_cycle_duration_handler(float value) {
    auto *v = ventilation_ctrl;
    v->set_cycle_duration((uint32_t)value * 1000);
}

/// @brief Converts a minutes value from the UI slider to ms and updates sync interval.
inline void set_sync_interval_handler(float value) {
    auto *v = ventilation_ctrl;
    v->set_sync_interval((uint32_t)value * 60 * 1000);
}

/// @brief Handles the fan intensity slider: updates global, notifies controller, refreshes LEDs.
inline void set_fan_intensity_slider(float value) {
    int val = (int)value;
    fan_intensity_level->value() = val;
    // set_fan_intensity_level(val); // Removed as undefined
    
    ventilation_ctrl->set_fan_intensity(val);
    update_leds->execute();
}

/// @brief Handles the mode select dropdown: maps string option to VentilationMode.
inline void set_operating_mode_select(std::string x) {
    auto *v = ventilation_ctrl;
    if (x == "Wärmerückgewinnung") {
        v->set_mode(esphome::MODE_ECO_RECOVERY);
    } else if (x == "Stoßlüftung") {
        v->set_mode(esphome::MODE_STOSSLUEFTUNG);
    } else if (x == "Durchlüften") {
        // Use the configured timer duration (0 = Infinite)
        uint32_t duration = (uint32_t)(vent_timer->state * 60 * 1000);
        v->set_mode(esphome::MODE_VENTILATION, duration);
    } else if (x == "Aus") {
        v->set_mode(esphome::MODE_OFF);
    }
    update_leds->execute();
}

// --- Button callback handlers ------------------------------------------

/// @brief Mode button press: cycles mode index 0→1→2→3→0 and applies.
inline void handle_button_mode_click() {
    current_mode_index->value() = (current_mode_index->value() + 1) % 4;
    cycle_operating_mode(current_mode_index->value());
    update_leds->execute();
}

/// @brief Power button press: toggles ventilation_enabled on/off.
/// ON restores previous mode + fan speed; OFF stops fan and PWM outputs.
inline void handle_button_power_click() {
    ventilation_enabled->value() = !ventilation_enabled->value();
    if (ventilation_enabled->value()) {
        // Power ON: Restore previous mode and fan speed
        ESP_LOGI("power", "System ON - restoring mode %d", current_mode_index->value());
        cycle_operating_mode(current_mode_index->value());
        fan_speed_update->execute();
    } else {
        // Power OFF: Stop fan and set mode to OFF
        ESP_LOGI("power", "System OFF");
        auto *v = ventilation_ctrl;
        v->set_mode(esphome::MODE_OFF);
        lueftung_fan->turn_off();
        fan_pwm_primary->set_level(0.0);
        fan_pwm_secondary->set_level(0.0);
    }
    update_leds->execute();
}

/// @brief Level button press: cycles fan intensity 1→10→1 and updates UI + hardware.
inline void handle_button_level_click() {
    if (!ventilation_enabled->value()) return;  // Ignore if system is off
    int level = fan_intensity_level->value();
    
    // Delegate logic to Pure Class
    level = VentilationLogic::get_next_fan_level(level);
    
    fan_intensity_level->value() = level;
    fan_intensity_display->publish_state(level);
    
    ventilation_ctrl->set_fan_intensity(level);
    fan_speed_update->execute();
    update_leds->execute();
    ESP_LOGI("button", "Intensity level: %d", level);
}
