# ==========================================================================
# VentoSync HRV – ESPHome NO SENSOR configuration
# ==========================================================================

substitutions:
  hide_climate_sensors: "true"

esphome:
  platformio_options:
    build_flags:
      - "-DVENTOSYNC_NO_CLIMATE"
      - "-DVENTOSYNC_NO_RADAR"

packages:
  base: !include ventosync_base.yaml
  mock_climate: !include packages/sensors/mock_climate.yaml
  mock_radar: !include packages/sensors/mock_radar.yaml
