# ==========================================================================
# VentoSync HRV – ESPHome RADAR ONLY configuration
# ==========================================================================

substitutions:
  hide_climate_sensors: "true"

esphome:
  platformio_options:
    build_flags:
      - "-DVENTOSYNC_NO_CLIMATE"

packages:
  base: !include ventosync_base.yaml
  mock_climate: !include packages/sensors/mock_climate.yaml
  ld2450: !include packages/sensors/sensor_LD2450.yaml
