#pragma once

/// @file automation_helpers.h
/// @brief Inline helper functions called from ESPHome YAML lambdas.
/// Bridges the gap between YAML automations and the C++ VentilationController /
/// VentilationLogic classes.  Also declares all `extern` pointers that ESPHome
/// code-gen provides for globals, scripts, lights, outputs, fan, etc.

#include "esphome.h"
#include <algorithm>
#include <string>
#include <vector>
#include <deque>

// Core and Component Headers
#include "esphome/components/globals/globals_component.h"
#include "esphome/components/script/script.h"
#include "esphome/components/template/select/template_select.h"
#include "esphome/components/template/number/template_number.h"
#include "esphome/components/template/switch/template_switch.h"
#include "esphome/components/output/float_output.h"
#include "esphome/components/light/light_state.h"
#include "esphome/components/binary_sensor/binary_sensor.h"
#include "esphome/components/homeassistant/sensor/homeassistant_sensor.h"
#include "esphome/components/ntc/ntc.h"
// Custom Component Header
#include "esphome/components/ventilation_group/ventilation_group.h"
#include "esphome/components/ventilation_logic/ventilation_logic.h"

// --- Extern declarations -----------------------------------------------
// Generated by ESPHome code-gen; IDs must match YAML component `id:` values.

/// @name Global variables
/// @{
extern esphome::globals::GlobalsComponent<bool> *system_on;            ///< Master power state.
extern esphome::globals::GlobalsComponent<bool> *ventilation_enabled;   ///< Ventilation enabled flag.
extern esphome::globals::GlobalsComponent<int> *current_mode_index;     ///< Active mode index (0–3).
extern esphome::globals::GlobalsComponent<int> *fan_intensity_level;    ///< Fan intensity (1–10).
extern esphome::globals::RestoringGlobalsComponent<bool> *co2_auto_enabled;      ///< CO2 auto-control enabled flag.
extern esphome::globals::RestoringGlobalsComponent<int> *automatik_min_fan_level;  ///< Min fan level for auto control (moisture protection).
extern esphome::globals::RestoringGlobalsComponent<int> *automatik_max_fan_level;  ///< Max fan level for auto control (noise limit).

extern esphome::globals::GlobalsComponent<bool> *auto_mode_active;
extern esphome::globals::RestoringGlobalsComponent<int> *auto_co2_threshold_val;
extern esphome::globals::RestoringGlobalsComponent<int> *auto_humidity_threshold_val;
extern esphome::globals::RestoringGlobalsComponent<int> *auto_presence_val;
extern esphome::globals::GlobalsComponent<float> *co2_pid_result;
extern esphome::globals::GlobalsComponent<float> *humidity_pid_result;
/// @}

/// @name Template UI components
/// @{
extern esphome::template_::TemplateSelect *luefter_modus;       ///< Mode selector (WRG/Stoß/Durchlüften/Aus).
// auto_presence_behavior removed
extern esphome::template_::TemplateNumber *vent_timer;          ///< Ventilation timer (minutes).
extern esphome::template_::TemplateNumber *fan_intensity_display; ///< Fan intensity display number.
extern esphome::template_::TemplateSwitch *automatik_co2;       ///< CO2 auto-control on/off switch.
extern esphome::template_::TemplateNumber *automatik_min_luefterstufe; ///< Min fan level for automated modes.
extern esphome::template_::TemplateNumber *automatik_max_luefterstufe; ///< Max fan level for automated modes.
extern esphome::template_::TemplateNumber *auto_presence_slider; ///< Presence compensation slider.
extern esphome::template_::TemplateNumber *auto_co2_threshold;   ///< CO2 automated threshold.
extern esphome::template_::TemplateNumber *auto_humidity_threshold; ///< Humidity automated threshold.
extern esphome::template_::TemplateNumber *sync_interval_config; ///< Time between auto-sync packets in minutes.
/// @}

extern esphome::globals::GlobalsComponent<bool> *ui_active;     ///< UI active flag (30s dimming).
extern esphome::globals::RestoringGlobalsComponent<bool> *peer_check_enabled; ///< ESP-NOW peer check on/off.
extern esphome::template_::TemplateSwitch *peer_check_switch;   ///< HA switch for peer check.

/// @name Scripts
/// @{
extern esphome::script::RestartScript<> *update_leds;         ///< Refreshes all status LEDs.
extern esphome::script::RestartScript<> *ui_timeout_script;   ///< UI 30s timeout script.
extern esphome::script::RestartScript<> *fan_speed_update;    ///< Re-applies fan speed.
extern esphome::script::SingleScript<float, int> *set_fan_speed_and_direction; ///< Sets PWM + direction.
/// @}

/// @name Fan hardware
/// @{
extern esphome::speed::SpeedFan *lueftung_fan;       ///< Main fan (speed platform).
extern esphome::ledc::LEDCOutput *fan_pwm_primary;   ///< Primary PWM output (GPIO19).
/// @}

/// @name Sensors
/// @{
extern esphome::sensor::Sensor *scd41_co2;           ///< SCD41 CO2 sensor.
extern esphome::sensor::Sensor *temperature;         ///< Room Temperature (SCD41)
extern esphome::ntc::NTC *temp_zuluft;         ///< Supply Air Temperature (NTC Inside)
extern esphome::ntc::NTC *temp_abluft;         ///< Exhaust Air Temperature (NTC Outside)
extern esphome::sensor::Sensor *scd41_humidity;      ///< Indoor Humidity
extern esphome::homeassistant::HomeassistantSensor *outdoor_humidity;    ///< Outdoor Humidity (HA)
extern esphome::binary_sensor::BinarySensor *radar_presence; ///< Presence Sensor (Radar)
/// @}

/// @name Status LEDs (monochromatic light components)
/// @{
extern esphome::light::LightState *status_led_l1;        ///< Level indicator LED 1.
extern esphome::light::LightState *status_led_l2;        ///< Level indicator LED 2.
extern esphome::light::LightState *status_led_l3;        ///< Level indicator LED 3.
extern esphome::light::LightState *status_led_l4;        ///< Level indicator LED 4.
extern esphome::light::LightState *status_led_l5;        ///< Level indicator LED 5.
extern esphome::light::LightState *status_led_power;     ///< Power status LED.
extern esphome::light::LightState *status_led_master;    ///< Master status LED (error indicator).
extern esphome::light::LightState *status_led_mode_wrg;  ///< Mode LED: Wärmerückgewinnung.
extern esphome::light::LightState *status_led_mode_vent; ///< Mode LED: Ventilation.
/// @}

/// Ventilation controller component instance.
extern esphome::VentilationController *ventilation_ctrl;

// --- Inline wrappers (called from YAML lambdas) -----------------------

// Global constants
static const uint32_t PEER_TIMEOUT_MS = 300000;      // 5 minutes

/// Last PWM level sent to fan_pwm_primary via set_level() (0.0–1.0).
/// Used by the 'Lüfter PWM Ansteuerung' template sensor since LEDCOutput has no get_level().
static float last_fan_pwm_level = 0.5f;  // Default: Stop

/// @name NTC Stabilization Logic
/// @{

// Stabilization parameter constants
static const float NTC_MAX_DEVIATION = 0.3f;         // Max allowed deviation in window

// State for each NTC sensor (0 = zuluft, 1 = abluft)
static std::deque<float> ntc_history[2];
static uint32_t last_direction_change_time = 0;

/// Call this when fan direction (switch) changes
inline void notify_fan_direction_changed() {
    last_direction_change_time = millis();
    ntc_history[0].clear();
    ntc_history[1].clear();
    ESP_LOGD("ntc_filter", "Fan direction changed. Resetting NTC history buffers.");
}

/// NTC Sliding Window Stabilization Filter
/// @param sensor_idx 0 for temp_zuluft, 1 for temp_abluft
/// @param new_value The raw value reported by the physical NTC component
/// @return The original value if stable, else empty optional to discard update
inline esphome::optional<float> filter_ntc_stable(int sensor_idx, float new_value) {
    if (ventilation_ctrl == nullptr || ventilation_ctrl->state_machine.cycle_duration_ms == 0) {
        return new_value; // Fallback if controller is not bound
    }

    uint32_t cycle_duration_ms = ventilation_ctrl->state_machine.cycle_duration_ms;
    
    // Dynamic wait time: 60% of the cycle, but minimum 20 seconds
    uint32_t wait_time_ms = std::max((uint32_t)20000, (uint32_t)(cycle_duration_ms * 0.6f));
    
    // Safety check so we don't wait longer than the cycle itself minus 5s
    if (wait_time_ms >= cycle_duration_ms) {
        wait_time_ms = cycle_duration_ms > 5000 ? cycle_duration_ms - 5000 : 0;
    }

    // Dynamic window size based on remaining time in the cycle
    // Values arrive every 3 seconds (as specified in yaml median filter send_every)
    uint32_t remaining_time_ms = cycle_duration_ms > wait_time_ms ? cycle_duration_ms - wait_time_ms : 0;
    size_t target_window_size = std::max((size_t)1, (size_t)(remaining_time_ms / 3000));

    // 1. Check if we are still within the mandatory thermal adjustment wait time
    if (millis() - last_direction_change_time < wait_time_ms) {
        return {}; // Discard value while ceramic adjusts 
    }

    // 2. Add current value to history window
    auto &history = ntc_history[sensor_idx];
    history.push_back(new_value);
    
    // Maintain maximum window size limit
    while (history.size() > target_window_size) {
        history.pop_front();
    }

    // 3. Wait until the window is full for a reliable stabilization check
    if (history.size() < target_window_size) {
        return {}; // Discard value while checking buffer window fills up
    }

    // 4. Calculate deviation
    auto [min_it, max_it] = std::minmax_element(history.begin(), history.end());
    float min_val = *min_it;
    float max_val = *max_it;

    // 5. Evaluate stability
    if ((max_val - min_val) <= NTC_MAX_DEVIATION) {
        // Temperature is stable!
        return new_value;
    } else {
        // Still fluctuating, keep last known state
        return {}; 
    }
}
/// @}


/// @brief Returns a human-readable German CO2 classification.
inline std::string get_co2_classification(float co2_ppm) {
  return VentilationLogic::get_co2_classification(co2_ppm);
}

/// @brief Calculates CO2-based fan level with hysteresis.
inline int get_co2_fan_level(float co2_ppm, int current_level, int min_level, int max_level) {
  return VentilationLogic::get_co2_fan_level(co2_ppm, current_level, min_level, max_level);
}

/// @brief Applies CO2-based auto-control if enabled and SCD41 is connected.
/// Checks sensor availability (NaN = not connected), calculates target level,
/// and applies it only if it differs from the current level (gradual change).
inline void apply_co2_auto_control() {
    // Guard: System-wide Automatik mode must be active
    if (auto_mode_active == nullptr || !auto_mode_active->value()) return;

    // Guard: CO2 auto-control (switch) must be enabled
    if (!co2_auto_enabled->value()) return;

    // Guard: System must be on
    if (!ventilation_enabled->value()) return;

    // Guard: SCD41 sensor must be connected (state is NaN when absent)
    if (scd41_co2 == nullptr) return;
    float co2_ppm = scd41_co2->state;
    if (std::isnan(co2_ppm)) {
        ESP_LOGD("co2_auto", "SCD41 not connected — CO2 auto-control inactive");
        return;
    }

    int current_level = fan_intensity_level->value();
    int min_level = automatik_min_fan_level->value();
    int max_level = automatik_max_fan_level->value();

    int target_level = VentilationLogic::get_co2_fan_level(co2_ppm, current_level, min_level, max_level);

    if (target_level != current_level) {
        ESP_LOGI("co2_auto", "CO2=%.0f ppm → Fan %d→%d (min=%d, max=%d)",
                 co2_ppm, current_level, target_level, min_level, max_level);
        fan_intensity_level->value() = target_level;
        fan_intensity_display->publish_state(target_level);
        ventilation_ctrl->set_fan_intensity(target_level);
        fan_speed_update->execute();
        update_leds->execute();
    }
}

/// @brief Core logic for the new Standard-Automatik mode.
inline void evaluate_auto_mode() {
    if (!auto_mode_active->value() || !system_on->value() || !ventilation_enabled->value()) return;

    auto *v = ventilation_ctrl;
    // Default to the configured base level from Home Assistant (Moisture protection / base ventilation)
    int target_level = automatik_min_fan_level->value(); 
    int internal_mode = v->state_machine.current_mode; // Copy current mode as starting point

    // Determine current hardware direction to correctly map NTC sensors during MODE_VENTILATION
    if (v == nullptr) return;
    const bool is_intake = v->state_machine.get_target_state(millis()).direction_in;

    // --- 1. Compute Local Temperatures ---
    float local_in = NAN;
    float local_out = NAN;

    // SCD41 is always a valid indoor temperature if available
    if (temperature != nullptr && !std::isnan(temperature->state)) {
        local_in = temperature->state;
    }

    if (internal_mode == esphome::MODE_VENTILATION) {
        // Continuous flow mode: NTC sensors show true external/internal air depending on direction
        if (is_intake) {
            // Blowing IN: Exhaust NTC gets true outside air, Supply NTC gets mixed/flow air (ignore)
            if (temp_abluft != nullptr) local_out = temp_abluft->state;
        } else {
            // Blowing OUT: Supply NTC gets true inside air, Exhaust NTC gets mixed/flow (ignore)
            if (std::isnan(local_in) && temp_zuluft != nullptr) local_in = temp_zuluft->state;
        }
    } else if (internal_mode == esphome::MODE_ECO_RECOVERY) {
        // WRG mode: Stable NTC values are valid representations (thanks to the 45s filter logic)
        if (temp_abluft != nullptr) local_out = temp_abluft->state;
        if (std::isnan(local_in) && temp_zuluft != nullptr) local_in = temp_zuluft->state;
    }
    
    // Store in controller for ESP-NOW broadcast
    v->local_t_in = local_in;
    v->local_t_out = local_out;

    // --- 2. Compute Effective Temperatures (Group-wide) ---
    float eff_in = local_in;
    float eff_out = local_out;
    
    const uint32_t now = millis();
    // Use peer indoor temp if local is missing and peer value is fresh (<5 mins)
    if (std::isnan(eff_in) && !std::isnan(v->last_peer_t_in) && (now - v->last_peer_t_in_time < PEER_TIMEOUT_MS)) {
        eff_in = v->last_peer_t_in;
    }
    // Use peer outdoor temp if local is missing and peer value is fresh (<5 mins)
    if (std::isnan(eff_out) && !std::isnan(v->last_peer_t_out) && (now - v->last_peer_t_out_time < PEER_TIMEOUT_MS)) {
        eff_out = v->last_peer_t_out;
    }

    // --- 3. Summer Cooling Logic ---
    if (!std::isnan(eff_in) && !std::isnan(eff_out)) {
        if (internal_mode != esphome::MODE_VENTILATION) {
            // Check if we should ENGAGE cooling (Inside too warm, outside is cooler)
            if (eff_in > 22.0f && eff_out < eff_in) {
                internal_mode = esphome::MODE_VENTILATION;
                ESP_LOGI("auto_mode", "Summer cooling engaged: In=%.1fC, Out=%.1fC", eff_in, eff_out);
            } else if (internal_mode != esphome::MODE_ECO_RECOVERY) {
                // Return to eco recovery
                internal_mode = esphome::MODE_ECO_RECOVERY;
            }
        } else {
            // Check if we should ABORT cooling (Outside got warmer than inside)
            if (eff_out >= eff_in) {
                internal_mode = esphome::MODE_ECO_RECOVERY;
                ESP_LOGI("auto_mode", "Summer cooling aborted (Too warm outside): In=%.1fC, Out=%.1fC", eff_in, eff_out);
            }
        }
    } else if (internal_mode != esphome::MODE_ECO_RECOVERY && internal_mode != esphome::MODE_VENTILATION) {
         // Default to WRG
         internal_mode = esphome::MODE_ECO_RECOVERY;
    }

    // --- 4. Air Quality logic (CO2 & Humidity via PID) ---
    float max_pid_demand = 0.0f;

    if (co2_auto_enabled->value() && co2_pid_result != nullptr) {
        max_pid_demand = std::max(max_pid_demand, co2_pid_result->value());
    }

    if (scd41_humidity != nullptr && outdoor_humidity != nullptr) {
        const float in_hum = scd41_humidity->state;
        const float out_hum = outdoor_humidity->state;
        
        if (!std::isnan(in_hum) && !std::isnan(out_hum)) {
            if (out_hum < in_hum && humidity_pid_result != nullptr) {
                // Only use humidity demand if outdoor is drier
                max_pid_demand = std::max(max_pid_demand, humidity_pid_result->value());
            }
        }
    }

    // Save local demand to controller for ESP-NOW broadcast
    // Every second, this device tells the group how much ventilation it currently demands.
    v->local_pid_demand = max_pid_demand;

    // Compare with peer demand if fresh (<5 mins)
    // Synchronized ESP-NOW PID Logic:
    // If a peer device in the same room reports a higher air-clearing demand (because someone
    // is breathing near it, or humidity spiked locally), we adopt that higher demand.
    // This forces all devices in the room to scale up together symmetrically, preventing
    // situations where one device runs loudly at 100% while the other idles at 10%.
    if (!std::isnan(v->last_peer_pid_demand) && (now - v->last_peer_pid_demand_time < PEER_TIMEOUT_MS)) {
        max_pid_demand = std::max(max_pid_demand, v->last_peer_pid_demand);
    }

    if (max_pid_demand > 0.01f) {
        int min_level = automatik_min_fan_level->value();
        int max_level = automatik_max_fan_level->value();
        
        // Calculate proportional LED target level (1-10 display feedback)
        // Note: The physical motor receives a precision float (0.0 - 1.0) via update_fan_logic()
        // for absolutely silent, stepless transitions. This 'target_level' is kept just so the
        // intensity LEDs on the unit faceplate show a representative average.
        float scaled_level = min_level + max_pid_demand * (max_level - min_level);
        target_level = std::max(target_level, (int)std::round(scaled_level));
        ESP_LOGD("auto_mode", "PID Demand=%.2f (Local=%.2f, Peer=%.2f) -> Boost level to %d", 
                  max_pid_demand, v->local_pid_demand, v->last_peer_pid_demand, target_level);
    }

    // 5. Presence logic
    if (radar_presence != nullptr && radar_presence->has_state() && radar_presence->state) {
        int presence_comp = auto_presence_val->value();
        if (presence_comp != 0) {
            target_level = std::max(1, std::min(10, target_level + presence_comp));
        }
    }

    // Apply the computed logic
    if (v->state_machine.current_mode != internal_mode) {
        v->set_mode((esphome::VentilationMode)internal_mode);
    }
    
    if (fan_intensity_level->value() != target_level) {
        fan_intensity_level->value() = target_level;
        fan_intensity_display->publish_state(target_level);
        ventilation_ctrl->set_fan_intensity(target_level);
        fan_speed_update->execute();
        update_leds->execute();
        ESP_LOGI("auto_mode", "Automode updated fan level to %d", target_level);
    }
}

/// @brief Sets fan PWM for the ebm-papst VarioPro reversible fan.
/// This fan uses a SINGLE PWM signal for both speed and direction:
///   - 50.0% duty cycle = STOP (active brake)
///   - 50% → 0%   = Direction: Zuluft (Stufe 1 @ 30%, Stufe 10 @ 5%)
///   - 50% → 100% = Direction: Abluft (Stufe 1 @ 70%, Stufe 10 @ 95%)
/// @param speed     Target speed as duty cycle fraction (0.1 = min, 1.0 = max).
/// @param direction Target direction: 0 = Zuluft (PWM < 50%), 1 = Abluft (PWM > 50%).
inline void set_fan_logic(float speed, int direction) {
    if (fan_pwm_primary == nullptr) return;

    // Clamp speed to valid range
    speed = std::max(0.0f, std::min(1.0f, speed));

    // Stop zone: below 5% speed or logical off
    if (speed < 0.05f) {
        fan_pwm_primary->set_level(0.50f);
        last_fan_pwm_level = 0.50f;
        return;
    }

    float pwm;
    if (direction == 0) {
        // Direction Zuluft: Min Speed (0.1) -> 30% PWM, Max Speed (1.0) -> 5% PWM
        // Linear interpolation: y = y1 + (x - x1) * (y2 - y1) / (x2 - x1)
        // PWM = 0.30 + (speed - 0.1) * (0.05 - 0.30) / (1.0 - 0.1)
        pwm = 0.30f - ((speed - 0.1f) / 0.9f) * 0.25f;
    } else {
        // Direction Abluft: Min Speed (0.1) -> 70% PWM, Max Speed (1.0) -> 95% PWM
        // PWM = 0.70 + (speed - 0.1) * (0.95 - 0.70) / (0.9)
        pwm = 0.70f + ((speed - 0.1f) / 0.9f) * 0.25f;
    }

    // Clamp to absolute hardware safety limits
    pwm = std::max(0.02f, std::min(0.98f, pwm));

    fan_pwm_primary->set_level(pwm);
    last_fan_pwm_level = pwm;
}

/// @brief Converts a user-facing level (1-10) to actual hardware PWM speed (10% - 100%)
inline float level_to_speed(float level) {
    static const float SPEED_MIN = 0.10f;  // Stufe 1 mapped to 10% PWM
    static const float MAX_FAN_LEVEL = 10.0f;
    return SPEED_MIN + ((level - 1.0f) / (MAX_FAN_LEVEL - 1.0f)) * (1.0f - SPEED_MIN);
}

/// @brief Calculates the exact target speed (0.0 to 1.0) based on intensity level and auto PID rules.
inline float get_current_target_speed() {
    if (fan_intensity_level == nullptr) return 0.0f;
    
    // Normal manual mode calculation
    float speed = level_to_speed((float)fan_intensity_level->value());

    if (auto_mode_active != nullptr && auto_mode_active->value()) {
        float max_pid_demand = 0.0f;
        if (co2_auto_enabled->value() && co2_pid_result != nullptr) {
            max_pid_demand = std::max(max_pid_demand, co2_pid_result->value());
        }
        if (humidity_pid_result != nullptr) {
             max_pid_demand = std::max(max_pid_demand, humidity_pid_result->value());
        }
        if (ventilation_ctrl != nullptr) {
            const uint32_t now = millis();
            if (!std::isnan(ventilation_ctrl->last_peer_pid_demand) && (now - ventilation_ctrl->last_peer_pid_demand_time < PEER_TIMEOUT_MS)) {
                max_pid_demand = std::max(max_pid_demand, ventilation_ctrl->last_peer_pid_demand);
            }
        }
        
        float min_level = (float)automatik_min_fan_level->value();
        float max_level = (float)automatik_max_fan_level->value();
        
        if (max_pid_demand > 0.01f) {
            // Scale the PID demand (0.0 - 1.0) directly onto the Level domain (e.g. Stage 1 to Stage 8)
            float target_level = min_level + max_pid_demand * (max_level - min_level);
            speed = level_to_speed(target_level);
        } else {
            // When demand drops to 0, use the minimum defined limit
            speed = level_to_speed(min_level);
        }
    }
    return std::max(0.0f, std::min(1.0f, speed));
}

/// @brief Updates fan speed and direction based on intensity and mode.
/// Reads fan_direction switch for direction, calculates speed from intensity/PID,
/// then calls set_fan_logic() which maps both into the single VarioPro PWM signal.
inline void update_fan_logic() {
    if (fan_intensity_level == nullptr) return;
    const int intensity = fan_intensity_level->value();

    // Dynamic Cycle duration mapped to fan level:
    if (ventilation_ctrl != nullptr) {
        float dynamic_cycle_s = 70.0f - ((intensity - 1.0f) * (20.0f / 9.0f));
        uint32_t dynamic_cycle_ms = std::round(dynamic_cycle_s) * 1000;
        if (ventilation_ctrl->state_machine.cycle_duration_ms != dynamic_cycle_ms) {
            ventilation_ctrl->set_cycle_duration(dynamic_cycle_ms);
        }
    }

    float speed = get_current_target_speed();

    // Apply software ramping factor if a controller is available
    if (ventilation_ctrl != nullptr) {
        HardwareState state = ventilation_ctrl->state_machine.get_target_state(millis());
        speed *= state.ramp_factor;
        
        // Log ramping during transition phases for debugging
        if (state.ramp_factor < 0.99f && state.ramp_factor > 0.01f) {
            ESP_LOGD("fan_ramp", "Ramping speed: %.2f (Base: %.2f, Factor: %.2f)", 
                      speed, get_current_target_speed(), state.ramp_factor);
        }
    }

    // Read current direction from the fan_direction switch:
    // OFF = Direction: Zuluft (PWM < 50%)
    // ON  = Direction: Abluft (PWM > 50%)
    const int direction = (fan_direction != nullptr && fan_direction->state) ? 1 : 0;

    set_fan_logic(speed, direction);
}

/// @brief Calculates heat-recovery efficiency as a percentage.
inline float calculate_heat_recovery_efficiency(float t_raum, float t_zuluft, float t_aussen) {
  return VentilationLogic::calculate_heat_recovery_efficiency(t_raum, t_zuluft, t_aussen);
}


/// @brief Returns true if the manual speed slider is below the off threshold.
inline bool is_fan_slider_off(float value) {
    return VentilationLogic::is_fan_slider_off(value);
}


/// @brief Linear ramp-up for soft fan start (0.0…1.0 over 100 iterations).
inline float calculate_ramp_up(int iteration) {
    return VentilationLogic::calculate_ramp_up(iteration);
}

/// @brief Linear ramp-down for soft fan stop (1.0…0.0 over 100 iterations).
inline float calculate_ramp_down(int iteration) {
    return VentilationLogic::calculate_ramp_down(iteration);
}


/// @brief Applies the operating mode corresponding to the given index.
/// Index mapping: 0 = Automatik, 1 = WRG, 2 = Durchlüften, 3 = Stoßlüftung, 4 = Aus.
/// Manages system_on/ventilation_enabled state, syncs HA select, and triggers fan update.
inline void cycle_operating_mode(int mode_index) {
  auto *v = ventilation_ctrl;
  auto_mode_active->value() = false; // Reset by default
  
  // Mode names for HA select sync (must match luefter_modus options exactly)
  static const char* mode_names[] = {"Automatik", "Wärmerückgewinnung", "Durchlüften", "Stoßlüftung", "Aus"};
  
  switch(mode_index) {
    case 0: // Automatik
      system_on->value() = true;
      ventilation_enabled->value() = true;
      auto_mode_active->value() = true;
      // Directly set mode to bypass set_mode() early-return guard
      // (Automatik and WRG both use MODE_ECO_RECOVERY)
      v->state_machine.current_mode = esphome::MODE_ECO_RECOVERY;
      v->update_hardware();
      v->pending_broadcast = true;
      evaluate_auto_mode(); // Immediate PID/sensor eval
      break;
    case 1:  // Wärmerückgewinnung (manual)
      system_on->value() = true;
      ventilation_enabled->value() = true;
      // Directly set mode to bypass set_mode() early-return guard
      v->state_machine.current_mode = esphome::MODE_ECO_RECOVERY;
      v->update_hardware();
      v->pending_broadcast = true;
      break;
    case 2:  // Durchlüften — timer from vent_timer number component
      system_on->value() = true;
      ventilation_enabled->value() = true;
      v->set_mode(esphome::MODE_VENTILATION, (uint32_t)(vent_timer->state * 60 * 1000));
      break;
    case 3:  // Stoßlüftung
      system_on->value() = true;
      ventilation_enabled->value() = true;
      v->set_mode(esphome::MODE_STOSSLUEFTUNG);
      break;
    case 4:  // Aus
      system_on->value() = false;
      ventilation_enabled->value() = false;
      v->set_mode(esphome::MODE_OFF);
      lueftung_fan->turn_off();
      fan_pwm_primary->set_level(0.5f); // Neutral stop for VarioPro
      break;
  }
  
  // Sync HA select dropdown
  if (mode_index >= 0 && mode_index <= 4) {
    std::string mode_str = mode_names[mode_index];
    if (std::string(luefter_modus->current_option()) != mode_str) {
      luefter_modus->publish_state(mode_str);
    }
  }
  
  // Update fan speed for active modes
  if (mode_index != 4) {
    fan_speed_update->execute();
  }
  
  ESP_LOGI("mode", "Mode changed to index %d", mode_index);
}


void check_master_led_error();

/// @brief Refreshes all status LEDs based on system_on, current mode, and fan level.
/// Maps fan intensity 1–10 onto the 5 level LEDs and toggles the two mode LEDs.
/// ALL LEDs (except Master error blink and Power LED) turn off when ui_active is false.
/// Power LED dims to 20% when ui_active is false.
inline void update_leds_logic() {
  auto *v = ventilation_ctrl;
  const int current_mode = v->state_machine.current_mode;

  // 0. Case: System is OFF
  if (!system_on->value()) {
    status_led_power->turn_off().perform();
    status_led_mode_wrg->turn_off().perform();
    status_led_mode_vent->turn_off().perform();
    status_led_l1->turn_off().perform();
    status_led_l2->turn_off().perform();
    status_led_l3->turn_off().perform();
    status_led_l4->turn_off().perform();
    status_led_l5->turn_off().perform();
    check_master_led_error(); // Still show error independently
    return;
  }

  // 1. Case: UI Inactive (Dimming/Night mode)
  if (!ui_active->value()) {
    // Dim Power LED to 20%
    status_led_power->turn_on().set_brightness(0.2f).perform();
    
    // Turn off all others
    status_led_mode_wrg->turn_off().perform();
    status_led_mode_vent->turn_off().perform();
    status_led_l1->turn_off().perform();
    status_led_l2->turn_off().perform();
    status_led_l3->turn_off().perform();
    status_led_l4->turn_off().perform();
    status_led_l5->turn_off().perform();
    
    check_master_led_error();
    return;
  }

  // 2. Case: UI Active and System On (Normal operation)
  
  // 1. Power LED (100% Brightness)
  status_led_power->turn_on().set_brightness(1.0f).perform();

  // 2. Mode LEDs
  status_led_mode_wrg->turn_off().perform();
  status_led_mode_vent->turn_off().perform();

  if (current_mode != esphome::MODE_OFF) {
    if (auto_mode_active->value()) {
      // Smart-Automatik: Left LED pulses slowly to distinguish from manual WRG
      auto call = status_led_mode_wrg->turn_on();
      call.set_effect("Automatik Pulse");
      call.perform();
    } else if (current_mode == esphome::MODE_ECO_RECOVERY) {
      // Manual WRG: Left LED solid on
      auto call = status_led_mode_wrg->turn_on();
      call.set_effect("None");
      call.perform();
    } else if (current_mode == esphome::MODE_STOSSLUEFTUNG) {
      // Stoßlüftung: Right LED on
      status_led_mode_vent->turn_on().perform();
    } else if (current_mode == esphome::MODE_VENTILATION) {
      // Durchlüften: Both LEDs on (solid)
      auto call_wrg = status_led_mode_wrg->turn_on();
      call_wrg.set_effect("None");
      call_wrg.perform();
      status_led_mode_vent->turn_on().perform();
    }
  }

  // 3. Level LEDs (1-10 mapped to 5 LEDs)
  // Reset all first
  status_led_l1->turn_off().perform();
  status_led_l2->turn_off().perform();
  status_led_l3->turn_off().perform();
  status_led_l4->turn_off().perform();
  status_led_l5->turn_off().perform();

  if (current_mode != esphome::MODE_OFF) {
    const int level = fan_intensity_level->value();
    
    // Mapping Logic (1-10 -> 5 LEDs)
    if (level >= 10) {
      status_led_l1->turn_on().perform(); status_led_l2->turn_on().perform();
      status_led_l3->turn_on().perform(); status_led_l4->turn_on().perform();
      status_led_l5->turn_on().perform();
    } else {
       switch(level) {
         case 1: status_led_l1->turn_on().perform(); break;
         case 2: status_led_l1->turn_on().perform(); status_led_l2->turn_on().perform(); break;
         case 3: status_led_l2->turn_on().perform(); break;
         case 4: status_led_l2->turn_on().perform(); status_led_l3->turn_on().perform(); break;
         case 5: status_led_l3->turn_on().perform(); break;
         case 6: status_led_l3->turn_on().perform(); status_led_l4->turn_on().perform(); break;
         case 7: status_led_l4->turn_on().perform(); break;
         case 8: status_led_l4->turn_on().perform(); status_led_l5->turn_on().perform(); break;
         case 9: status_led_l5->turn_on().perform(); break;
       }
    }
  }

  // Also ensure the Master LED evaluates its UI status immediately
  check_master_led_error();
}

/// @brief Checks for error conditions and blinks the Master LED accordingly.
/// Error conditions: WiFi disconnected OR no ESP-NOW peer message within 5 minutes.
/// Uses the "Error Blink" strobe effect defined on the status_led_master light.
inline void check_master_led_error() {
    bool has_error = false;

    // 1. Check WiFi connectivity (ESPHome API, works on both Arduino and ESP-IDF)
    if (!esphome::wifi::global_wifi_component->is_connected()) {
        has_error = true;
    }

    // 2. Check ESP-NOW peer freshness (5 minutes = 300000ms) — only if enabled
    if (peer_check_enabled != nullptr && peer_check_enabled->value() && ventilation_ctrl != nullptr) {
        const uint32_t now = millis();
        // If we have never received a peer message, or it's been > 5 minutes
        if (ventilation_ctrl->last_peer_pid_demand_time == 0 ||
            (now - ventilation_ctrl->last_peer_pid_demand_time > PEER_TIMEOUT_MS)) {
            has_error = true;
        }
    }

    // 3. Apply or remove the blink effect
    if (has_error) {
        // Only activate if not already blinking (avoid re-triggering every interval)
        auto call = status_led_master->turn_on();
        call.set_effect("Error Blink");
        call.perform();
    } else {
        // All clear: check if UI is active so we can show Master status, else turn off
        if (ui_active->value()) {
            auto call = status_led_master->turn_on();
            call.set_effect("None");
            call.perform();
        } else {
            status_led_master->turn_off().perform();
        }
    }
}

/// @brief Handles an incoming ESP-NOW packet.
/// Delegates parsing to VentilationController, then updates UI globals,
/// select component, LEDs, and fan speed if state changed.
inline void handle_espnow_receive(const std::vector<uint8_t>& data) {
    auto *v = ventilation_ctrl;
    bool changed = v->on_packet_received(data);

    if (changed) {
        // 1. Sync Fan Intensity
        if (v->current_fan_intensity != fan_intensity_level->value()) {
            fan_intensity_level->value() = v->current_fan_intensity;
            fan_intensity_display->publish_state(v->current_fan_intensity);
        }

        // 2. Sync Mode & Globals
        int new_mode_idx = 0;
        std::string mode_str = "Wärmerückgewinnung";

        if (v->state_machine.current_mode == esphome::MODE_OFF) {
            new_mode_idx = 4; mode_str = "Aus";
            ventilation_enabled->value() = false;
            system_on->value() = false;
            auto_mode_active->value() = false;
        } else {
            ventilation_enabled->value() = true;
            system_on->value() = true;
            
            if (auto_mode_active->value()) {
                 new_mode_idx = 0; mode_str = "Automatik";
            } else if (v->state_machine.current_mode == esphome::MODE_ECO_RECOVERY) { 
                new_mode_idx = 1; mode_str = "Wärmerückgewinnung"; 
            } else if (v->state_machine.current_mode == esphome::MODE_VENTILATION) { 
                new_mode_idx = 2; mode_str = "Durchlüften"; 
            } else if (v->state_machine.current_mode == esphome::MODE_STOSSLUEFTUNG) { 
                new_mode_idx = 3; mode_str = "Stoßlüftung"; 
            }
        }

        current_mode_index->value() = new_mode_idx;

        // Update Select Component if different
        if (std::string(luefter_modus->current_option()) != mode_str) {
            luefter_modus->publish_state(mode_str);
        }

        // Update Visuals
        update_leds->execute();
        fan_speed_update->execute();
    }
    
    // --- Configuration Settings Sync ---
    // ESP-NOW payloads carry all user settings. If another node has different
    // configuration values, we adopt them to ensure room-wide parity.
    esphome::VentilationPacket *pkt = (esphome::VentilationPacket*)data.data();

    // Guard against corrupt packets with out-of-range values that could crash/break logic
    bool dirty = false;
    
    // 1. CO2 Automatik (Switch)
    if (pkt->co2_auto_enabled != co2_auto_enabled->value()) {
        co2_auto_enabled->value() = pkt->co2_auto_enabled;
        automatik_co2->publish_state(pkt->co2_auto_enabled);
        ESP_LOGI("vent_sync", "Synced co2_auto_enabled from peer: %d", pkt->co2_auto_enabled);
        dirty = true;
    }

    // 2. Automatik Min/Max Levels (Sliders 1-10)
    if (pkt->automatik_min_fan_level >= 1 && pkt->automatik_min_fan_level <= 10 && pkt->automatik_min_fan_level != automatik_min_fan_level->value()) {
        automatik_min_fan_level->value() = pkt->automatik_min_fan_level;
        automatik_min_luefterstufe->publish_state(pkt->automatik_min_fan_level);
        ESP_LOGI("vent_sync", "Synced automatik_min_fan_level from peer: %d", pkt->automatik_min_fan_level);
        dirty = true;
    }

    if (pkt->automatik_max_fan_level >= 1 && pkt->automatik_max_fan_level <= 10 && pkt->automatik_max_fan_level != automatik_max_fan_level->value()) {
        automatik_max_fan_level->value() = pkt->automatik_max_fan_level;
        automatik_max_luefterstufe->publish_state(pkt->automatik_max_fan_level);
        ESP_LOGI("vent_sync", "Synced automatik_max_fan_level from peer: %d", pkt->automatik_max_fan_level);
        dirty = true;
    }

    // 3. Automatik Thresholds (Numbers)
    if (pkt->auto_co2_threshold_val >= 400 && pkt->auto_co2_threshold_val <= 5000 && pkt->auto_co2_threshold_val != auto_co2_threshold_val->value()) {
        auto_co2_threshold_val->value() = pkt->auto_co2_threshold_val;
        auto_co2_threshold->publish_state(pkt->auto_co2_threshold_val);
        ESP_LOGI("vent_sync", "Synced auto_co2_threshold from peer: %d ppm", pkt->auto_co2_threshold_val);
        dirty = true;
    }

    if (pkt->auto_humidity_threshold_val >= 0 && pkt->auto_humidity_threshold_val <= 100 && pkt->auto_humidity_threshold_val != auto_humidity_threshold_val->value()) {
        auto_humidity_threshold_val->value() = pkt->auto_humidity_threshold_val;
        auto_humidity_threshold->publish_state(pkt->auto_humidity_threshold_val);
        ESP_LOGI("vent_sync", "Synced auto_humidity_threshold from peer: %d %%", pkt->auto_humidity_threshold_val);
        dirty = true;
    }

    // 4. Presence Compensation Slider (-5 to +5)
    if (pkt->auto_presence_val >= -5 && pkt->auto_presence_val <= 5 && pkt->auto_presence_val != auto_presence_val->value()) {
        auto_presence_val->value() = pkt->auto_presence_val;
        auto_presence_slider->publish_state(pkt->auto_presence_val);
        ESP_LOGI("vent_sync", "Synced auto_presence_val from peer: %d", pkt->auto_presence_val);
        dirty = true;
    }

    // 5. System Timers
    if (pkt->sync_interval_min >= 1 && pkt->sync_interval_min <= 1440) {
        if (v->sync_interval_ms != (uint32_t)(pkt->sync_interval_min * 60 * 1000)) {
            v->set_sync_interval(pkt->sync_interval_min * 60 * 1000);
            sync_interval_config->publish_state(pkt->sync_interval_min);
        }
    }

    if (pkt->vent_timer_min <= 1440 && (uint32_t)(pkt->vent_timer_min * 60 * 1000) != v->state_machine.ventilation_duration_ms) {
        v->state_machine.ventilation_duration_ms = pkt->vent_timer_min * 60 * 1000;
        vent_timer->publish_state(pkt->vent_timer_min);
        ESP_LOGI("vent_sync", "Synced vent_timer from peer: %d min", pkt->vent_timer_min);
        // Note: setting the timer does not change the active mode.
    }

    // If any configs changed, re-evaluate standard logic immediately to reflect new boundaries.
    if (dirty) {
        evaluate_auto_mode();
    }
}

/// @brief Updates the ventilation duration on-the-fly without switching mode.
/// Called when the user adjusts the vent_timer number component.
inline void set_ventilation_timer(float value) {
    auto *v = ventilation_ctrl;
    uint32_t ms = (uint32_t)value * 60 * 1000;
    // Update the duration but keep current mode
    v->state_machine.ventilation_duration_ms = ms;
}

/// @brief Converts a minutes value from the UI slider to ms and updates sync interval.
inline void set_sync_interval_handler(float value) {
    auto *v = ventilation_ctrl;
    v->set_sync_interval((uint32_t)value * 60 * 1000);
}

/// @brief Handles the fan intensity slider: updates global, notifies controller, refreshes LEDs.
inline void set_fan_intensity_slider(float value) {
    int val = (int)value;
    fan_intensity_level->value() = val;
    
    ventilation_ctrl->set_fan_intensity(val);
    fan_speed_update->execute();
    ui_active->value() = true;
    update_leds->execute();
    ui_timeout_script->execute();
}

/// @brief Handles the mode select dropdown from HA: maps string option to mode index
/// and delegates to cycle_operating_mode() for unified state management.
inline void set_operating_mode_select(const std::string& x) {
    int mode_index = 0;
    if (x == "Automatik")           mode_index = 0;
    else if (x == "Wärmerückgewinnung") mode_index = 1;
    else if (x == "Durchlüften")    mode_index = 2;
    else if (x == "Stoßlüftung")    mode_index = 3;
    else if (x == "Aus")            mode_index = 4;
    
    current_mode_index->value() = mode_index;
    cycle_operating_mode(mode_index);
    ui_active->value() = true;
    update_leds->execute();
    ui_timeout_script->execute();
}

// --- Button callback handlers ------------------------------------------

/// @brief Mode button press: cycles mode index 0→1→2→3→4→0 and applies.
inline void handle_button_mode_click() {
    current_mode_index->value() = (current_mode_index->value() + 1) % 5;
    cycle_operating_mode(current_mode_index->value());
    ui_active->value() = true;         // Activate UI immediately so LEDs render
    update_leds->execute();            // Show new mode LEDs now
    ui_timeout_script->execute();      // Start 30s auto-dim timer
    ESP_LOGI("button", "Mode button pressed, new index: %d", current_mode_index->value());
}

/// @brief Power button short press: turns ventilation_enabled ON.
/// Restores previous mode + fan speed.
inline void handle_button_power_short_click() {
    if (!ventilation_enabled->value()) {
        ventilation_enabled->value() = true;
        ESP_LOGI("power", "System turned ON by short press - restoring mode %d", current_mode_index->value());
        cycle_operating_mode(current_mode_index->value());
        fan_speed_update->execute();
        ui_timeout_script->execute();
    } else {
        ESP_LOGD("power", "System already ON, ignoring short press");
    }
}

/// @brief Power button long press (>=5s): turns ventilation_enabled OFF.
/// Stops fan and PWM outputs.
inline void handle_button_power_long_click() {
    if (ventilation_enabled->value()) {
        ventilation_enabled->value() = false;
        ESP_LOGI("power", "System turned OFF by long press (>5s)");
        auto *v = ventilation_ctrl;
        v->set_mode(esphome::MODE_OFF);
        lueftung_fan->turn_off();
        fan_pwm_primary->set_level(0.0);
        ui_timeout_script->execute();
    } else {
        ESP_LOGD("power", "System already OFF, ignoring long press");
    }
}

/// @brief Level button press: cycles fan intensity 1→10→1 and updates UI + hardware.
inline void handle_button_level_click() {
    if (!ventilation_enabled->value()) return;  // Ignore if system is off
    int level = fan_intensity_level->value();
    
    // Delegate logic to Pure Class
    level = VentilationLogic::get_next_fan_level(level);
    
    fan_intensity_level->value() = level;
    fan_intensity_display->publish_state(level);
    
    ventilation_ctrl->set_fan_intensity(level);
    fan_speed_update->execute();
    ui_active->value() = true;         // Activate UI immediately so LEDs render
    update_leds->execute();            // Show new intensity level LEDs now
    ui_timeout_script->execute();      // Start 30s auto-dim timer
    ESP_LOGI("button", "Intensity level: %d", level);
}

/// @brief Central wrapper to create a fully populated VentilationPacket.
/// Calls the standard C++ class method to build the base layout, and then appends
/// the local Home Assistant configuration variables to ensure they traverse the network.
inline std::vector<uint8_t> build_and_populate_packet(esphome::MessageType type) {
    auto *v = ventilation_ctrl;
    // Get the base vector containing the core logic payload
    std::vector<uint8_t> data = v->build_packet(type);
    
    // Cast it to our known struct
    esphome::VentilationPacket *pkt = (esphome::VentilationPacket*)data.data();

    // Populate all HA configurations
    pkt->co2_auto_enabled = co2_auto_enabled->value();
    pkt->automatik_min_fan_level = (uint8_t) automatik_min_fan_level->value();
    pkt->automatik_max_fan_level = (uint8_t) automatik_max_fan_level->value();
    pkt->auto_co2_threshold_val = (uint16_t) auto_co2_threshold_val->value();
    pkt->auto_humidity_threshold_val = (uint8_t) auto_humidity_threshold_val->value();
    pkt->auto_presence_val = (int8_t) auto_presence_val->value();
    
    // Timers
    pkt->sync_interval_min = (uint16_t) (v->sync_interval_ms / 60 / 1000);
    pkt->vent_timer_min = (uint16_t) (v->state_machine.ventilation_duration_ms / 60 / 1000);

    return data;
}
