# ==========================================================================
# WRG Wohnraumlüftung – SCD41 CO2, Temperature & Humidity Sensor
# https://github.com/thomasengeroff-dotcom/VentoSync
#
# File:        sensor_SCD41.yaml
# Description: Configuration for SCD41 CO2 sensor.
#              Includes CO2, temperature, humidity, and calibration.
# ==========================================================================

sensor:
  # ---------------------------------------------------------
  # SCD41 CO2 SENSOR (Optional)
  # ---------------------------------------------------------
  # Will show as "unavailable" until sensor is connected to H2 header
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
      id: scd41_co2
      accuracy_decimals: 0
      filters:
        - median:
            window_size: 5
            send_every: 3
    temperature_offset: 4.0 # Optional: default value is 4.0 °C
    altitude_compensation: 250m # Replace 250m with your location's altitude
    automatic_self_calibration: true
    temperature:
      name: "SCD41 Temperatur"
      id: scd41_temperature
      accuracy_decimals: 1
    humidity:
      name: "SCD41 Luftfeuchtigkeit"
      id: scd41_humidity
      accuracy_decimals: 1
