name: ESPHome Config Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  lint:
    name: Validate YAML Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Create dummy secrets.yaml
        run: cp secrets_example.yaml secrets.yaml

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install ESPHome
        run: pip install esphome==2026.3.1

      - name: Verify Configuration
        run: esphome config ventosync.yaml
